name: TEST Deployment

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Promote dev → test on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/bhs-frontend:dev
            docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/bhs-frontend:dev ghcr.io/${{ secrets.GHCR_USERNAME }}/bhs-frontend:test
            docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/bhs-frontend:test
            docker stop bhs-frontend-test || true
            docker rm bhs-frontend-test || true
            docker run -d --name bhs-frontend-test -p 8082:80 ghcr.io/${{ secrets.GHCR_USERNAME }}/bhs-frontend:test

