name: TEST Deployment

on:
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build test image
        run: |
          docker build --no-cache --build-arg BUILD_ENV=test -t ghcr.io/fabianauinger/bhs-frontend:test .

      - name: Push test image
        run: docker push ghcr.io/fabianauinger/bhs-frontend:test

      - name: SSH Deploy to Test Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull ghcr.io/fabianauinger/bhs-frontend:test || echo "Image not found, skipping pull"
            docker stop bhs-frontend-test || true || echo "Container not running, skipping stop"
            docker rm bhs-frontend-test || true || echo "Container not found, skipping remove"
            docker run -d --name bhs-frontend-test -p 8082:80 ghcr.io/fabianauinger/bhs-frontend:test


