name: TEST Deployment

on:
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    env:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Pull dev base image
        run: docker pull ghcr.io/${GHCR_USERNAME}/bhs-frontend:dev

      - name: Build test image based on dev
        run: |
          docker build --build-arg BUILD_ENV=test -t ghcr.io/${GHCR_USERNAME}/bhs-frontend:test .

      - name: Push test image
        run: docker push ghcr.io/${GHCR_USERNAME}/bhs-frontend:test

      - name: SSH Deploy to Test Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TEST_SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull ghcr.io/${GHCR_USERNAME}/bhs-frontend:test
            docker stop bhs-frontend-test || true
            docker rm bhs-frontend-test || true
            docker run -d --name bhs-frontend-test -p 8082:80 ghcr.io/${GHCR_USERNAME}/bhs-frontend:test


